name: test-deploy
run-name: test-deploy

on: workflow_dispatch

env:
  GITHUB_PAT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --release && cp ./target/release/multi_repo_orchestration_tool ./

      - name: run
        run: ./multi_repo_orchestration_tool -n orchestration.yml
